### PR TITLE
Fr cors fix

### LINKED ISSUE #22: Cors Bug Fix
Configure rack cors gem, so fe can hit api calls

### PR DESCRIPTION
**Pull request by fredrondina**
### Issue(s) related to this PR:
* closes #22 

### Type of change made:
* [x] Bugfix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] Styling- no new features

#### If this submission is a new feature:
* [x] Have you added an explanation of what your changes do?
* [x] Have you lint your code locally prior to submission?

### Change Log:
* Set up rack cors gem, and configured in application.rb. FE should now be able to hit api from their end

### Were there any challenges that arose? If so, how were the addressed?
* no

### Technical Debt:
* none added

### Testing:
* [ ] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] All new and existing tests passed?
* [x] Have you run linter?

**Test coverage** = 100% test coverage (No change)

### CODE REVIEW

File: config/application.rb [hunk 1]
```diff
@@ -22,6 +22,12 @@ class Application < Rails::Application
     # Initialize configuration defaults for originally generated Rails version.
     config.load_defaults 5.2
 
+    config.middleware.insert_before 0, Rack::Cors do
```
Comment (tylertomlinson) [inline config/application.rb:25]: NIce fix

**Review by tylertomlinson — APPROVED** [review]

File: config/application.rb (hunk 1 above)
Comment (fredrondina) [reply config/application.rb:25]: Thanks
